In [1]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
             
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [2]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [3]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [4]:
x1 = np.array([[1,2,3],[4,5,6]])
print(x1)

[[1 2 3]
 [4 5 6]]


In [5]:
x2 = np.array([[1],[2]])
print(x2)

[[1]
 [2]]


In [6]:
x3 = x1 + x2
print(x3)

[[2 3 4]
 [6 7 8]]


In [7]:
x4 = x1 * x2
print(x4)

[[ 1  2  3]
 [ 8 10 12]]


In [8]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c)


[[  2.8795351   -4.98758047  -2.55930549 ... -11.41296014  11.48116468
    8.83732777]
 [  2.06393227 -15.71247195 -24.12118765 ... -13.78479349  -9.39797149
    8.06377582]
 [  1.7275454    2.69832866  -2.16156692 ...   2.49615065  -2.54637141
   16.83639857]
 ...
 [  4.75436463   5.42345072  -2.17364138 ...  15.22169781  -7.19056718
   -0.9500174 ]
 [-12.31820483  10.18109363  -7.98801926 ...  10.94178892  15.22510064
    1.79118369]
 [ -0.73788263 -11.15206658 -20.29081913 ... -10.73027273   6.71028313
   -6.83834753]]


In [9]:
print(c.shape)

(12288, 45)


In [10]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [11]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)

[[ 3.83355932 -0.29046304 -0.15181939]
 [ 1.33284818  0.98315923  0.52816872]
 [ 0.63569132  0.38971546 -0.33084206]]
